# Inicio de base dataos de la pafina Oficial Mysql version 5.7
FROM postgres:11.17-alpine3.16

# Comment
RUN echo 'Base de datos Inicial de la pafina Oficial # excelente'
LABEL base_datos_mysql="postgres11.17"





